- name: Play Level Variables
  hosts: locals
  vars:
    my_variable: "Play Level"
  tasks:
    - name: Print my_variable
      ansible.builtin.debug:
        msg: "Hello from {{ my_variable }} variable."