- name: Check whether number is divisible by 2
  hosts: locals
  connection: local
  gather_facts: no

  vars_prompt:
    - name: NUM
      prompt: Enter a number
      private: false

  tasks:
    - name: Number is divisible by 2
      ansible.builtin.debug:
        msg: "The number {{ NUM }} is divisible by 2."
      when: NUM | int is even

    - name: Number is NOT divisible by 2
      ansible.builtin.debug:
        msg: "The number {{ NUM }} is NOT divisible by 2."
      when: NUM | int is odd
