- name: Install required package
  hosts: locals
  connection: local
  become: yes
  vars_prompt:
    - name: PKG_NAME
      prompt: Enter package Name
      private: false
  tasks:
    - name: task package to install
      ansible.builtin.package:
        name: "{{ PKG_NAME }}"
        state: present

