- name: play to install/uninstall packages
  hosts: locals
  connection: local
  tasks: 
    - name: task to install or uninstall packages
      ansible.builtin.package:
        name: "{{ item.pkg_name }}"
        state: "{{ item.pkg_status }}"
      loop:
      - { pkg_name: 'mysql-server', pkg_status: 'present'}
      - { pkg_name: 'htop', pkg_status: 'absent'}
      - { pkg_name: 'curl', pkg_status: 'present'}