- name: Split Play
  hosts: locals
  connection: local
  vars:
    tech: "C;C++;Java;Python;C#"
  tasks:
  - name: split task
    ansible.builtin.debug:
      msg: "Hello, {{ tech | split(';') }} !"
